### PR TITLE
 Philosophy: Added introductory resources

### PR DESCRIPTION
**Pull request by dxwc**
Contains:

+ Mainly Phil of mind related resources
+ Some more non-academic resources
+ An avoid-list

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Thank you a lot for this. I will merge it and will translate it all to the mind map in a bit.

There's a lot of things there. 💙

**Comment by nikitavoloboev** [comment]
Can I ask based on what criteria you included the people in the AVOID list?

**Comment by dxwc** [comment]
- Repeated mistakes/oversimplifications (Crash Course Philosophy)
- Oversimplification of philosophical topics, mixed with over-generalizations from psychology and neuroscience, mixed with personal ideologies - to make insanely large philosophical claims, while branding it as either science or philosophy (Sam Harris)
- Use of philosophical terms and creating self-help video - but branding it as philosophy nevertheless (School of Life) 
- Repeated oversimplification/Mixing personal ideology to re-interpret philosophers (Jordan B. Peterson)
- Making big claims about AI without any philosophical basis (Elon Musk, Ray Kurzweil)
- I've seen a video where he over-generalized psychological research to make claim about localization of consciousness in some parts of the brain, making something the "you" (https://en.wikipedia.org/wiki/Cartesian_materialism) -- a big claim, for which no basis is presented, but explained as if it is established fact - and also managed to sprinkle in the impossible that this can somehow cause problem for free will... (CGP Grey)
- I'm actually unfamiliar with any of his work if there is any, but every time I clicked on one of the millions of youtube videos of him talking - I only found self-help blabbering that doesn't make any sense. It is possible I'm wrong on this one. (Alan Watts)

**Comment by tdoskocil** [comment]
I'm very interested in this. I've been wanting to create a mind map like concept builder off 📺 shot of phone. Visualized research and digital journal. Any advice would be appreciated

**Pull request merged**
